# -*- coding: utf-8 -*-
"""PCA_Digits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L28enGM6MDj1PGKhBOFfmaD6EaN0Lu0U
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

digits = load_digits()

X = digits.data
y= digits.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr_original = LogisticRegression(max_iter=1000)
lr_original.fit(X_train_scaled, y_train)

y_pred_original = lr_original.predict(X_test_scaled)
original_acc = accuracy_score(y_test, y_pred_original)

print("Accuracy (Original Data):", round(original_acc,4))

components_list = [2, 10, 30, 50, 55, 60]
pca_results = {}

for n in components_list:
    pca = PCA(n_components=n)
    X_train_pca = pca.fit_transform(X_train_scaled)
    X_test_pca = pca.transform(X_test_scaled)

    lr = LogisticRegression(max_iter=1000)
    lr.fit(X_train_pca, y_train)

    y_pred = lr.predict(X_test_pca)
    acc = accuracy_score(y_test, y_pred)

    pca_results[n] = acc
    print(f"Accuracy with {n} components:", round(acc,4))

pca_full = PCA()
pca_full.fit(X_train_scaled)

cum_var = np.cumsum(pca_full.explained_variance_ratio_)

plt.figure(figsize=(8,5))
plt.plot(cum_var, marker='o')
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("Explained Variance vs Components")
plt.grid()
plt.show()

pca_2d = PCA(n_components=2)
X_2d = pca_2d.fit_transform(X_train_scaled)

plt.figure(figsize=(8,6))
scatter = plt.scatter(X_2d[:,0], X_2d[:,1], c=y_train, cmap='tab10')
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA 2D Visualization")
plt.colorbar(scatter)
plt.show()

print("\nFinal Comparison:")
print("Original Accuracy:", round(original_acc,4))
for k,v in pca_results.items():
    print(f"PCA {k} components Accuracy:", round(v,4))

